###############################################################################
# Hosts lazy pillar
###############################################################################

{% set fqdn     = stack['DAConfig']['fqdn'] %}
{% set hostname = fqdn.split('.')[0] %}
{% set domain   = fqdn.split('.')[1:] | join('.') %}

hosts:
  fqdn: {{ fqdn }}
  hostname: {{ hostname }}
  domain: {{ domain }}
